# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa739c045e875fe542377ecf46515336f1208427231c8f0ccefacc41454b7cb9f9c96b48632afb46a2af339c5c7cca6e53bdc95e8342e95b9bfc67922e9ebd2e

test:
  secret_key_base: d39d11df85efffd459243a16a3c582266f3e27ff4147513a2b52949cf8bac874ba146f34b0b64eb3ae9659d028929ddf784e2fb72f7780982787ac488e6ccd1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
